Import the libraries needed.

In [2]:
import os
import sys

from shutil import copyfile
import pandas as pd

First. clean up the picture field

In [3]:
ppl_file = 'clean_lab.csv'
df = pd.read_csv(ppl_file)df

,picture,first_name,last_name,description,web_page,visitor,e_mail,alumni,public,current,mid_name,rank_id,rank
0,vigna.png,Giovanni,Vigna,Giovanni Vigna is a Professor in the Departmen...,http://www.cs.ucsb.edu/~vigna,0,vigna@cs.ucsb.edu,0,1,1,NaN,1,Faculty
1,chris2.jpg,Christopher,Kruegel,NaN,http://www.cs.ucsb.edu/~chris,0,chris@cs.ucsb.edu,0,1,1,NaN,1,Faculty
2,machiry.png,Aravind,Machiry,NaN,https://machiry.github.io/,0,machiry@cs.ucsb.edu,0,1,1,Kumar,3,PhD Students
3,nilo.jpg,Nilo,Redini,NaN,http://www.badnack.it/,0,badnack@cs.ucsb.edu,0,1,1,NaN,3,PhD Students
4,edg_profile.png,Eric,Gustafson,NaN,http://seclab.cs.ucsb.edu/,0,edg@cs.ucsb.edu,0,1,1,NaN,3,PhD Students
...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,NaN,Jason,Berry,NaN,NaN,0,NaN,1,1,0,NaN,6,Master Student
80,chani.jpeg,Chani,Jindal,NaN,NaN,0,NaN,1,1,0,NaN,6,Master Student
81,NaN,Keith,Long,NaN,NaN,0,NaN,1,1,0,NaN,6,Master Student
82,NaN,John,Grosen,NaN,NaN,0,NaN,1,1,0,NaN,7,Undergrad
83,NaN,Paul,Grosen,NaN,NaN,0,NaN,1,1,0,NaN,7,Undergrad

In [5]:
df.picture.replace(pd.NA, 'alias.jpeg',inplace=True)
df

,picture,first_name,last_name,description,web_page,visitor,e_mail,alumni,public,current,mid_name,rank_id,rank
0,vigna.png,Giovanni,Vigna,Giovanni Vigna is a Professor in the Departmen...,http://www.cs.ucsb.edu/~vigna,0,vigna@cs.ucsb.edu,0,1,1,NaN,1,Faculty
1,chris2.jpg,Christopher,Kruegel,NaN,http://www.cs.ucsb.edu/~chris,0,chris@cs.ucsb.edu,0,1,1,NaN,1,Faculty
2,machiry.png,Aravind,Machiry,NaN,https://machiry.github.io/,0,machiry@cs.ucsb.edu,0,1,1,Kumar,3,PhD Students
3,nilo.jpg,Nilo,Redini,NaN,http://www.badnack.it/,0,badnack@cs.ucsb.edu,0,1,1,NaN,3,PhD Students
4,edg_profile.png,Eric,Gustafson,NaN,http://seclab.cs.ucsb.edu/,0,edg@cs.ucsb.edu,0,1,1,NaN,3,PhD Students
...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,alias.jpeg,Jason,Berry,NaN,NaN,0,NaN,1,1,0,NaN,6,Master Student
80,chani.jpeg,Chani,Jindal,NaN,NaN,0,NaN,1,1,0,NaN,6,Master Student
81,alias.jpeg,Keith,Long,NaN,NaN,0,NaN,1,1,0,NaN,6,Master Student
82,alias.jpeg,John,Grosen,NaN,NaN,0,NaN,1,1,0,NaN,7,Undergrad
83,alias.jpeg,Paul,Grosen,NaN,NaN,0,NaN,1,1,0,NaN,7,Undergrad

In [6]:
df.to_csv('new.csv')